/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class commu_beyond_devcommudemo_DevCommuJni */

#ifndef _Included_commu_beyond_devcommudemo_DevCommuJni
#define _Included_commu_beyond_devcommudemo_DevCommuJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     commu_beyond_devcommudemo_DevCommuJni
 * Method:    SendCmdMsg
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_commu_beyond_devcommudemo_DevCommuJni_SendCmdMessage
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
